require('dotenv').config();
const express = require('express');
const morgan = require('morgan');
const cors = require('cors');
const helmet = require('helmet');
const { NODE_ENV } = require('./config');
const usersRouter = require('./users/users-router');
const eventsRouter = require('./events/events-router');
const contactsRouter = require('./contacts/contacts-router');
const app = express();
const morganOption = NODE_ENV === 'production' ? 'tiny' : 'common';
const authToken = require('./middleware/jwtAuth');
const errorHandler = require('./middleware/errorHandler');

app.use(morgan(morganOption));
app.use(helmet());
app.use(cors());
app.use(errorHandler);
app.use('/api/users', usersRouter);
app.use(authToken);
app.use('/api/events', eventsRouter);
app.use('/api/contacts', contactsRouter);
module.exports = app;
